joinfaces:
  faces:
    project-stage: development
server:
  servlet:
    context-path: /project
  tomcat:
    accesslog:
      enabled: true
spring:
  application:
    name: joinfaces-demo
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true